config/routes.rb
ContentEngine::Engine.routes.draw do
	resources :blogs
	mount AuthenticationEngine::Engine => "/"
end

app/models/content_engine/application_record.rb
module ContentEngine
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/content_engine/blog.rb
module ContentEngine
  class Blog < ApplicationRecord
  	has_many :comments
  	accepts_nested_attributes_for :comments
  	belongs_to :user, class_name: AuthenticationEngine::User
  	## Validations
  	validates :name, :description, presence: true
  end
end

app/models/content_engine/comment.rb
module ContentEngine
  class Comment < ApplicationRecord
  	belongs_to :blog
    belongs_to :user, class_name: AuthenticationEngine::User
  end
end

app/controllers/content_engine/application_controller.rb
module ContentEngine
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :current_user

    private

    def current_user
    	if session[:user_id].present?    		
    		@current_user = AuthenticationEngine::User.find_by(id: session[:user_id])
    	else
    		@current_user = nil
            redirect_to '/'
    	end 
    end

  end
end

app/controllers/content_engine/blogs_controller.rb
require_dependency "content_engine/application_controller"

module ContentEngine
  class BlogsController < ApplicationController
    before_action :set_blog, only: [:show, :edit, :update, :destroy]
    
    # GET /blogs
    def index
      @blogs = Blog.all
    end

    # GET /blogs/1
    def show
    end

    # GET /blogs/new
    def new
      @blog = Blog.new
    end

    # GET /blogs/1/edit
    def edit
    end

    # POST /blogs
    def create
      @blog = Blog.new(blog_params)
      @blog.user_id = @current_user.id 
      if @blog.save
        redirect_to @blog, notice: 'Blog successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /blogs/1
    def update
      if @blog.update(blog_params)
        redirect_to @blog, notice: 'Blog successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /blogs/1
    def destroy
      @blog.destroy
      redirect_to blogs_url, notice: 'Blog successfully deleted.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_blog
        @blog = Blog.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def blog_params
        params.require(:blog).permit(:name, :description, :user_id, comments_attributes: [:id, :content, :user_id, :blog_id, :'_destroy'])
      end
  end
end

app/controllers/content_engine/welcome_controller.rb
require_dependency "content_engine/application_controller"

module ContentEngine
  class WelcomeController < ApplicationController
    def index
    end
  end
end

app/helpers/content_engine/application_helper.rb
module ContentEngine
  module ApplicationHelper
  end
end

app/helpers/content_engine/blogs_helper.rb
module ContentEngine
  module BlogsHelper
  end
end

app/helpers/content_engine/welcome_helper.rb
module ContentEngine
  module WelcomeHelper
  end
end

app/views/content_engine/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control'  %>
  </div>  
  <hr>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Back', blogs_path, class: 'btn btn-primary' %>
    <% unless blog.new_record? %>
      <%= link_to 'Show', @blog, class: 'btn btn-primary' %>
    <% end %>
  </div>
<% end %>

app/views/content_engine/blogs/edit.html.erb
<h1>Editing Blog</h1>
<%= render 'form', blog: @blog %>

app/views/content_engine/blogs/index.html.erb
<h1>
  Blogs
  <small class="pull-right">
    <h4><%= link_to 'New Blog', new_blog_path, class: 'btn btn-sm btn-primary' %></h4>
  </small>
</h1>
<hr>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.id %></td>
        <td><%= blog.name %></td>
        <td><%= link_to blog.try(:user).try(:email_or_fullname_or_username), "/users/#{blog.user_id}" %></td>
        <td>
          <%= link_to 'Show', blog, class: 'btn btn-sm btn-primary' %>
          <% if blog.user_id == @current_user.id %>
            <%= link_to 'Edit', edit_blog_path(blog), class: 'btn btn-sm btn-primary' %>
            <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/content_engine/blogs/new.html.erb
<h1>New Blog</h1>
<hr>
<%= render 'form', blog: @blog %>

app/views/content_engine/blogs/show.html.erb
<h1>
  View Blog
  <small class="pull-right">
    <h4><%= link_to 'New Blog', new_blog_path, class: 'btn btn-sm btn-primary' %></h4>
  </small>
</h1>
<hr>

<p>
  <strong>Name:</strong>
  <%= @blog.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @blog.description %>
</p>

<p>
  By <%= link_to @blog.try(:user).email_or_fullname_or_username, "/users/#{@blog.user_id}" %>
</p>

<% if @blog.comments.present? %>
  <h4><b>Comments</b></h4>
  <div>
    <% @blog.comments.each do |comment| %>
      <p>
        <% if comment.user_id.present? %>
          <%= link_to comment.user.email_or_fullname_or_username, "/users/#{(comment.user_id)}" %>
        <% end %>
        <%= comment.content %>
      </p>
      <hr style="margin:0px;">
    <% end %>
  </div>
<% end %>

<%= nested_form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h3>Comments</h3>
  <div class="field">
    <%= f.fields_for :comments, f.object.comments.build do |cform| %>
      <% if @current_user.present? %>
        <%= cform.hidden_field :user_id, value: @current_user.id %>
      <% end %>
      <%= cform.label :content, 'Comment Message' %>
      <%= cform.text_field :content, class: 'form-control', required: 'required' %>
    <% end %>
  </div>
  <hr>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
    <% if @blog.user_id == @current_user.id %>
      <%= link_to 'Edit', edit_blog_path(@blog), class: 'btn btn-primary' %>
    <% end %>
    <%= link_to 'Back', blogs_path, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/content_engine/welcome/index.html.erb
<h1>Welcome#index</h1>

app/views/layouts/content_engine/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>Authentication engine</title>
  		<%= stylesheet_link_tag    "content_engine/application", media: "all" %>
  		<%= javascript_include_tag "content_engine/application" %>
  		<%= csrf_meta_tags %>
	</head>
	<body cz-shortcut-listen="true">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Engine Demo</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class=""><a href="/">Home</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>	
    <div class="container">
 			<% flash.each do |name, msg| %>
    		<%= content_tag :div, msg, class: "alert alert-info" %>
  		<% end %>
  		<br/>
      <% if @current_user.present? %>
        <%= link_to 'Logout', '/users/sign_out', method: :delete, data: {confirm: 'Are you sure want to logout?'}, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'Sign In', '/users/sign_in', data: {disable_with: 'Loading...'}, class: 'btn btn-primary' %>
        <%= link_to 'Sign Up', '/users/new', data: {disable_with: 'Loading...'}, class: 'btn btn-primary' %>
      <% end %>  		
			<%= yield %>
		</div>
	</body>
</html>